import type { Question } from '../../core/models/question.model';
export const SALUD_QUESTIONS: Question[] = [
  {
    id: 'q01',
    question: '¿Cuándo podemos decir que tenemos una buena salud?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'Cuando nos sentimos bien física, mental y socialmente',
        correct: true,
        emoji: '🌟',
      },
      { id: 'b', text: 'Solo cuando no tenemos fiebre', correct: false, emoji: '🌡️' },
      { id: 'c', text: 'Solo cuando hacemos mucho deporte', correct: false, emoji: '🏃' },
    ],
    explanation: 'La salud incluye tres aspectos: físico, mental y social.',
    hint: 'Recuerda las tres patas de la salud.',
  },
  {
    id: 'q02',
    question: 'Lucía corre, salta y juega sin dolor ni dificultades. ¿De qué salud hablamos?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Salud social', correct: false, emoji: '👫' },
      { id: 'b', text: 'Salud física', correct: true, emoji: '🏃‍♀️' },
      { id: 'c', text: 'Salud mental', correct: false, emoji: '😊' },
    ],
    explanation: 'La salud física está relacionada con el buen funcionamiento de nuestro cuerpo.',
    hint: 'Piensa en el cuerpo.',
  },
  {
    id: 'q03',
    question:
      'Carlos está contento consigo mismo y sabe manejar sus emociones. ¿Qué salud está cuidando?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Salud física', correct: false, emoji: '💪' },
      { id: 'b', text: 'Salud social', correct: false, emoji: '👥' },
      { id: 'c', text: 'Salud mental', correct: true, emoji: '😊' },
    ],
    explanation:
      'La salud mental tiene que ver con cómo nos sentimos y manejamos nuestras emociones.',
    hint: 'La pista está en sus emociones.',
  },
  {
    id: 'q04',
    question: 'Ana se relaciona bien con su familia y sus compañeros. ¿Qué tipo de salud aparece?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Salud social', correct: true, emoji: '👫' },
      { id: 'b', text: 'Salud física', correct: false, emoji: '🏃' },
      { id: 'c', text: 'Salud mental', correct: false, emoji: '🧠' },
    ],
    explanation: 'Relacionarnos bien con otras personas forma parte de la salud social.',
    hint: 'Piensa en la relación con los demás.',
  },
  {
    id: 'q05',
    question: '¿Qué significa prevenir?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'Intentar evitar problemas de salud antes de que aparezcan',
        correct: true,
        emoji: '🛡️',
      },
      { id: 'b', text: 'Esperar siempre a estar enfermos', correct: false, emoji: '🤒' },
      { id: 'c', text: 'No ir nunca al médico', correct: false, emoji: '🚫' },
    ],
    explanation: 'Prevenir es realizar acciones que ayudan a evitar daños o problemas de salud.',
    hint: 'Prevenir ocurre antes del problema.',
  },
  {
    id: 'q06',
    question: '¿Cuál de estos es un hábito saludable?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Hacer ejercicio con frecuencia', correct: true, emoji: '🚴' },
      { id: 'b', text: 'Dormir muy poco todos los días', correct: false, emoji: '🥱' },
      { id: 'c', text: 'Comer siempre chucherías', correct: false, emoji: '🍬' },
    ],
    explanation: 'El ejercicio es uno de los hábitos que ayuda a cuidar nuestra salud.',
    hint: 'Busca la acción que ayuda a tu cuerpo.',
  },
  {
    id: 'q07',
    question: '¿Para qué sirven las revisiones médicas?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Para detectar posibles problemas de salud', correct: true, emoji: '🩺' },
      { id: 'b', text: 'Solo para saber cuánto medimos', correct: false, emoji: '📏' },
      { id: 'c', text: 'Para no tener que hacer ejercicio', correct: false, emoji: '🛋️' },
    ],
    explanation:
      'Las revisiones permiten comprobar nuestro estado de salud y detectar problemas pronto.',
    hint: 'El médico comprueba cómo estamos.',
  },
  {
    id: 'q08',
    question: '¿Para qué sirven las vacunas?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Para ayudar a prevenir algunas enfermedades', correct: true, emoji: '💉' },
      { id: 'b', text: 'Para correr más rápido', correct: false, emoji: '⚡' },
      { id: 'c', text: 'Para sustituir una alimentación saludable', correct: false, emoji: '🍎' },
    ],
    explanation: 'Las vacunas nos ayudan a protegernos frente a determinadas enfermedades.',
    hint: 'Son una medida de prevención.',
  },
  {
    id: 'q09',
    question:
      'Si alguien se lleva muy bien con los demás, pero tiene dolor y dificultades para moverse, ¿su salud física está bien?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Sí, porque tiene amigos', correct: false, emoji: '👫' },
      { id: 'b', text: 'No, porque su cuerpo tiene dificultades', correct: true, emoji: '🩺' },
    ],
    explanation: 'Podemos tener un aspecto de la salud bien y otro que necesite atención.',
    hint: 'La pregunta habla específicamente de salud física.',
  },
  {
    id: 'q10',
    question: '¿Cuál de estas acciones ayuda a prevenir problemas de salud?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Tener hábitos saludables y acudir a revisiones médicas',
        correct: true,
        emoji: '🌟',
      },
      { id: 'b', text: 'Esperar siempre a encontrarnos mal', correct: false, emoji: '⌛' },
      { id: 'c', text: 'Ignorar las recomendaciones de salud', correct: false, emoji: '🙈' },
    ],
    explanation: 'Los hábitos saludables y las revisiones médicas forman parte de la prevención.',
    hint: 'Busca dos acciones que hacemos antes de tener un problema.',
  },
  {
    id: 'q11',
    question: '¿Cuál de estas situaciones es un ejemplo de salud social?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Hablar y jugar respetuosamente con los compañeros',
        correct: true,
        emoji: '🤝',
      },
      { id: 'b', text: 'Tener los músculos fuertes', correct: false, emoji: '💪' },
      { id: 'c', text: 'Reconocer que hoy estoy triste', correct: false, emoji: '😢' },
    ],
    explanation:
      'La salud social se relaciona con cómo convivimos y nos relacionamos con otras personas.',
    hint: 'Busca una situación en la que aparecen otras personas.',
  },
  {
    id: 'q12',
    question: '¿Cuál de estas situaciones está relacionada con la salud mental?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Saber reconocer que estoy enfadado y calmarme',
        correct: true,
        emoji: '🧠',
      },
      { id: 'b', text: 'Saltar muy alto', correct: false, emoji: '🤸' },
      { id: 'c', text: 'Llevarme bien con mis vecinos', correct: false, emoji: '🏘️' },
    ],
    explanation: 'Reconocer y manejar nuestras emociones forma parte de la salud mental.',
    hint: 'Piensa en emociones.',
  },
  {
    id: 'q13',
    question: 'Marcos come variado, duerme bien y hace ejercicio. ¿Qué está practicando?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Hábitos saludables', correct: true, emoji: '🌱' },
      { id: 'b', text: 'Una revisión médica', correct: false, emoji: '🩺' },
      { id: 'c', text: 'Una vacuna', correct: false, emoji: '💉' },
    ],
    explanation: 'Alimentarse bien, descansar y hacer ejercicio son hábitos saludables.',
    hint: 'Son cosas que hacemos habitualmente.',
  },
  {
    id: 'q14',
    question: '¿Cuál de estas frases es correcta?',
    difficulty: 'hard',
    points: 20,
    answers: [
      { id: 'a', text: 'La salud solo depende de que el cuerpo funcione bien', correct: false },
      { id: 'b', text: 'La salud tiene aspectos físicos, mentales y sociales', correct: true },
      { id: 'c', text: 'La salud social y la mental significan lo mismo', correct: false },
    ],
    explanation: 'Para sentirnos bien debemos tener en cuenta la salud física, mental y social.',
    hint: 'Recuerda las tres partes estudiadas.',
  },
  {
    id: 'q15',
    question: '¿Qué profesional puede ayudarnos a cuidar nuestra salud en una revisión infantil?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Un pediatra o una pediatra', correct: true, emoji: '👩‍⚕️' },
      { id: 'b', text: 'Un piloto', correct: false, emoji: '✈️' },
      { id: 'c', text: 'Un carpintero', correct: false, emoji: '🪚' },
    ],
    explanation:
      'Los pediatras son profesionales sanitarios especializados en la salud de niños y niñas.',
    hint: 'Piensa en quién te atiende en el centro de salud.',
  },
  {
    id: 'q16',
    question: '¿Dónde podemos acudir cuando necesitamos atención sanitaria?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'A centros de salud, hospitales o servicios de urgencias',
        correct: true,
        emoji: '🏥',
      },
      { id: 'b', text: 'Solo al colegio', correct: false, emoji: '🏫' },
      { id: 'c', text: 'A una tienda de juguetes', correct: false, emoji: '🧸' },
    ],
    explanation: 'Existen distintos servicios sanitarios para atender los problemas de salud.',
    hint: 'Busca lugares donde trabajan profesionales sanitarios.',
  },
  {
    id: 'q17',
    question:
      'Paula está preocupada y habla con una persona de confianza sobre cómo se siente. ¿Qué aspecto de su salud está cuidando especialmente?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'La salud mental', correct: true, emoji: '💛' },
      { id: 'b', text: 'La salud física', correct: false, emoji: '💪' },
      { id: 'c', text: 'Ninguno', correct: false, emoji: '❌' },
    ],
    explanation:
      'Hablar de nuestras emociones y aprender a manejarlas ayuda a cuidar la salud mental.',
    hint: 'Se refiere a cómo se siente Paula.',
  },
  {
    id: 'q18',
    question: '¿Qué tienen en común los hábitos saludables, las revisiones y las vacunas?',
    difficulty: 'hard',
    points: 20,
    answers: [
      { id: 'a', text: 'Son formas de prevención', correct: true, emoji: '🛡️' },
      { id: 'b', text: 'Solo se hacen cuando estamos enfermos', correct: false },
      { id: 'c', text: 'Son tipos de salud social', correct: false },
    ],
    explanation: 'Las tres son acciones que contribuyen a prevenir problemas y cuidar la salud.',
    hint: 'Piensa en el título de la segunda parte del tema.',
  },
  {
    id: 'q19',
    question: '¿Cuál de estos lugares es un servicio sanitario?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Un centro de salud', correct: true, emoji: '🩺' },
      { id: 'b', text: 'Un cine', correct: false, emoji: '🎬' },
      { id: 'c', text: 'Una biblioteca', correct: false, emoji: '📚' },
    ],
    explanation: 'Los centros de salud son servicios sanitarios.',
    hint: 'Piensa en un lugar al que acudimos para recibir atención sanitaria.',
  },
  {
    id: 'q20',
    question: '¿Qué tienen en común un centro de salud, un hospital y un servicio de urgencias?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Son servicios sanitarios', correct: true, emoji: '🏥' },
      { id: 'b', text: 'Son lugares para practicar deporte', correct: false, emoji: '⚽' },
      { id: 'c', text: 'Son centros educativos', correct: false, emoji: '🏫' },
    ],
    explanation: 'Los tres son servicios sanitarios que ayudan a atender problemas de salud.',
    hint: 'Todos están relacionados con la atención de nuestra salud.',
  },
  {
    id: 'q21',
    question: '¿Quién trabaja en los servicios sanitarios cuidando nuestra salud?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Profesionales especializados', correct: true, emoji: '👩‍⚕️' },
      { id: 'b', text: 'Solo deportistas', correct: false, emoji: '🏃' },
      { id: 'c', text: 'Solo músicos', correct: false, emoji: '🎵' },
    ],
    explanation:
      'En los servicios sanitarios trabajan profesionales especializados en cuidar nuestra salud.',
    hint: 'Piensa en las personas preparadas para atender problemas de salud.',
  },
  {
    id: 'q22',
    question:
      'Si necesitamos atención urgente por un problema de salud, ¿qué servicio aparece entre los que hemos estudiado?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'El servicio de urgencias', correct: true, emoji: '🚑' },
      { id: 'b', text: 'Una tienda', correct: false, emoji: '🛍️' },
      { id: 'c', text: 'Un museo', correct: false, emoji: '🏛️' },
    ],
    explanation: 'Los servicios de urgencias son uno de los servicios sanitarios estudiados.',
    hint: 'Su propio nombre indica que atiende situaciones urgentes.',
  },
  {
    id: 'q23',
    question: '¿Qué frase describe mejor la salud física?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Nuestro cuerpo funciona correctamente y realizamos actividades sin dolor ni dificultades',
        correct: true,
        emoji: '🏃‍♀️',
      },
      { id: 'b', text: 'Nos llevamos bien con otras personas', correct: false, emoji: '👫' },
      { id: 'c', text: 'Sabemos manejar nuestras emociones', correct: false, emoji: '😊' },
    ],
    explanation: 'La salud física está relacionada con el funcionamiento de nuestro cuerpo.',
    hint: 'Física = cuerpo.',
  },
  {
    id: 'q24',
    question: '¿Qué frase describe mejor la salud mental?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Estamos contentos con nosotros mismos y sabemos manejar nuestras emociones',
        correct: true,
        emoji: '😊',
      },
      { id: 'b', text: 'Nuestro cuerpo corre muy rápido', correct: false, emoji: '🏃' },
      { id: 'c', text: 'Tenemos muchos juguetes', correct: false, emoji: '🧸' },
    ],
    explanation:
      'La salud mental está relacionada con cómo nos sentimos y cómo manejamos nuestras emociones.',
    hint: 'Mental = emociones.',
  },
  {
    id: 'q25',
    question: '¿Qué frase describe mejor la salud social?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Nos relacionamos bien con las demás personas', correct: true, emoji: '🤝' },
      { id: 'b', text: 'Nunca necesitamos dormir', correct: false, emoji: '😴' },
      { id: 'c', text: 'Nuestro cuerpo no siente dolor', correct: false, emoji: '💪' },
    ],
    explanation: 'La salud social se refiere a nuestras relaciones con otras personas.',
    hint: 'Social = los demás.',
  },
  {
    id: 'q26',
    question: '¿Cuál de estas acciones NO es una forma de prevención de las que hemos estudiado?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Esperar a tener un problema para empezar a cuidarnos',
        correct: true,
        emoji: '⌛',
      },
      { id: 'b', text: 'Mantener hábitos saludables', correct: false, emoji: '🥗' },
      { id: 'c', text: 'Acudir a revisiones médicas', correct: false, emoji: '🩺' },
    ],
    explanation: 'La prevención consiste en actuar para intentar evitar problemas de salud.',
    hint: 'Busca la opción que ocurre después, no antes.',
  },
  {
    id: 'q27',
    question: 'Dormir lo necesario, alimentarnos bien y hacer actividad física son ejemplos de...',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Hábitos saludables', correct: true, emoji: '🌱' },
      { id: 'b', text: 'Servicios sanitarios', correct: false, emoji: '🏥' },
      { id: 'c', text: 'Vacunas', correct: false, emoji: '💉' },
    ],
    explanation: 'Son costumbres que ayudan a mantenernos sanos.',
    hint: 'Son acciones que repetimos habitualmente para cuidarnos.',
  },
  {
    id: 'q28',
    question: '¿Tenemos que esperar a encontrarnos mal para hacer una revisión médica?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'No, las revisiones también forman parte de la prevención',
        correct: true,
        emoji: '🩺',
      },
      { id: 'b', text: 'Sí, siempre', correct: false, emoji: '🤒' },
    ],
    explanation:
      'Las revisiones médicas ayudan a comprobar nuestro estado de salud y forman parte de la prevención.',
    hint: 'Prevenir significa actuar antes de que aparezca un problema.',
  },
  {
    id: 'q29',
    question: 'Completa la idea: física, mental y social son...',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Tres aspectos de la salud', correct: true, emoji: '🌟' },
      { id: 'b', text: 'Tres tipos de hospitales', correct: false, emoji: '🏥' },
      { id: 'c', text: 'Tres vacunas', correct: false, emoji: '💉' },
    ],
    explanation: 'La salud comprende los aspectos físico, mental y social.',
    hint: 'Son las tres partes que aparecen al explicar qué es la salud.',
  },
  {
    id: 'q30',
    question: 'Elige el resumen correcto sobre la prevención.',
    difficulty: 'hard',
    points: 20,
    answers: [
      {
        id: 'a',
        text: 'Los hábitos saludables, las revisiones médicas y las vacunas nos ayudan a cuidar la salud',
        correct: true,
        emoji: '🛡️',
      },
      {
        id: 'b',
        text: 'Prevenir significa no acudir nunca a servicios sanitarios',
        correct: false,
        emoji: '🚫',
      },
      {
        id: 'c',
        text: 'Solo podemos cuidar la salud cuando ya estamos enfermos',
        correct: false,
        emoji: '🤒',
      },
    ],
    explanation:
      'La prevención reúne acciones que realizamos para cuidar nuestra salud y tratar de evitar problemas.',
    hint: 'Recuerda las tres formas de prevención estudiadas.',
  },
];
