import type { Question } from '../../core/models/question.model';
export const SALUD_QUESTIONS: Question[] = [
  {
    id: 'q01',
    question: '¿Cuándo podemos decir que tenemos una buena salud?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'Cuando nos sentimos bien física, mental y socialmente',
        correct: true,
        emoji: '🌟',
      },
      { id: 'b', text: 'Solo cuando no tenemos fiebre', correct: false, emoji: '🌡️' },
      { id: 'c', text: 'Solo cuando hacemos mucho deporte', correct: false, emoji: '🏃' },
    ],
    explanation: 'La salud incluye tres aspectos: físico, mental y social.',
    hint: 'Recuerda las tres patas de la salud.',
  },
  {
    id: 'q02',
    question: 'Lucía corre, salta y juega sin dolor ni dificultades. ¿De qué salud hablamos?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Salud social', correct: false, emoji: '👫' },
      { id: 'b', text: 'Salud física', correct: true, emoji: '🏃‍♀️' },
      { id: 'c', text: 'Salud mental', correct: false, emoji: '😊' },
    ],
    explanation: 'La salud física está relacionada con el buen funcionamiento de nuestro cuerpo.',
    hint: 'Piensa en el cuerpo.',
  },
  {
    id: 'q03',
    question:
      'Carlos está contento consigo mismo y sabe manejar sus emociones. ¿Qué salud está cuidando?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Salud física', correct: false, emoji: '💪' },
      { id: 'b', text: 'Salud social', correct: false, emoji: '👥' },
      { id: 'c', text: 'Salud mental', correct: true, emoji: '😊' },
    ],
    explanation:
      'La salud mental tiene que ver con cómo nos sentimos y manejamos nuestras emociones.',
    hint: 'La pista está en sus emociones.',
  },
  {
    id: 'q04',
    question: 'Ana se relaciona bien con su familia y sus compañeros. ¿Qué tipo de salud aparece?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Salud social', correct: true, emoji: '👫' },
      { id: 'b', text: 'Salud física', correct: false, emoji: '🏃' },
      { id: 'c', text: 'Salud mental', correct: false, emoji: '🧠' },
    ],
    explanation: 'Relacionarnos bien con otras personas forma parte de la salud social.',
    hint: 'Piensa en la relación con los demás.',
  },
  {
    id: 'q05',
    question: '¿Qué significa prevenir?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'Intentar evitar problemas de salud antes de que aparezcan',
        correct: true,
        emoji: '🛡️',
      },
      { id: 'b', text: 'Esperar siempre a estar enfermos', correct: false, emoji: '🤒' },
      { id: 'c', text: 'No ir nunca al médico', correct: false, emoji: '🚫' },
    ],
    explanation: 'Prevenir es realizar acciones que ayudan a evitar daños o problemas de salud.',
    hint: 'Prevenir ocurre antes del problema.',
  },
  {
    id: 'q06',
    question: '¿Cuál de estos es un hábito saludable?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Hacer ejercicio con frecuencia', correct: true, emoji: '🚴' },
      { id: 'b', text: 'Dormir muy poco todos los días', correct: false, emoji: '🥱' },
      { id: 'c', text: 'Comer siempre chucherías', correct: false, emoji: '🍬' },
    ],
    explanation: 'El ejercicio es uno de los hábitos que ayuda a cuidar nuestra salud.',
    hint: 'Busca la acción que ayuda a tu cuerpo.',
  },
  {
    id: 'q07',
    question: '¿Para qué sirven las revisiones médicas?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Para detectar posibles problemas de salud', correct: true, emoji: '🩺' },
      { id: 'b', text: 'Solo para saber cuánto medimos', correct: false, emoji: '📏' },
      { id: 'c', text: 'Para no tener que hacer ejercicio', correct: false, emoji: '🛋️' },
    ],
    explanation:
      'Las revisiones permiten comprobar nuestro estado de salud y detectar problemas pronto.',
    hint: 'El médico comprueba cómo estamos.',
  },
  {
    id: 'q08',
    question: '¿Para qué sirven las vacunas?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Para ayudar a prevenir algunas enfermedades', correct: true, emoji: '💉' },
      { id: 'b', text: 'Para correr más rápido', correct: false, emoji: '⚡' },
      { id: 'c', text: 'Para sustituir una alimentación saludable', correct: false, emoji: '🍎' },
    ],
    explanation: 'Las vacunas nos ayudan a protegernos frente a determinadas enfermedades.',
    hint: 'Son una medida de prevención.',
  },
  {
    id: 'q09',
    question:
      'Si alguien se lleva muy bien con los demás, pero tiene dolor y dificultades para moverse, ¿su salud física está bien?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Sí, porque tiene amigos', correct: false, emoji: '👫' },
      { id: 'b', text: 'No, porque su cuerpo tiene dificultades', correct: true, emoji: '🩺' },
    ],
    explanation: 'Podemos tener un aspecto de la salud bien y otro que necesite atención.',
    hint: 'La pregunta habla específicamente de salud física.',
  },
  {
    id: 'q10',
    question: '¿Cuál de estas acciones ayuda a prevenir problemas de salud?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Tener hábitos saludables y acudir a revisiones médicas',
        correct: true,
        emoji: '🌟',
      },
      { id: 'b', text: 'Esperar siempre a encontrarnos mal', correct: false, emoji: '⌛' },
      { id: 'c', text: 'Ignorar las recomendaciones de salud', correct: false, emoji: '🙈' },
    ],
    explanation: 'Los hábitos saludables y las revisiones médicas forman parte de la prevención.',
    hint: 'Busca dos acciones que hacemos antes de tener un problema.',
  },
  {
    id: 'q11',
    question: '¿Cuál de estas situaciones es un ejemplo de salud social?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Hablar y jugar respetuosamente con los compañeros',
        correct: true,
        emoji: '🤝',
      },
      { id: 'b', text: 'Tener los músculos fuertes', correct: false, emoji: '💪' },
      { id: 'c', text: 'Reconocer que hoy estoy triste', correct: false, emoji: '😢' },
    ],
    explanation:
      'La salud social se relaciona con cómo convivimos y nos relacionamos con otras personas.',
    hint: 'Busca una situación en la que aparecen otras personas.',
  },
  {
    id: 'q12',
    question: '¿Cuál de estas situaciones está relacionada con la salud mental?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Saber reconocer que estoy enfadado y calmarme',
        correct: true,
        emoji: '🧠',
      },
      { id: 'b', text: 'Saltar muy alto', correct: false, emoji: '🤸' },
      { id: 'c', text: 'Llevarme bien con mis vecinos', correct: false, emoji: '🏘️' },
    ],
    explanation: 'Reconocer y manejar nuestras emociones forma parte de la salud mental.',
    hint: 'Piensa en emociones.',
  },
  {
    id: 'q13',
    question: 'Marcos come variado, duerme bien y hace ejercicio. ¿Qué está practicando?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Hábitos saludables', correct: true, emoji: '🌱' },
      { id: 'b', text: 'Una revisión médica', correct: false, emoji: '🩺' },
      { id: 'c', text: 'Una vacuna', correct: false, emoji: '💉' },
    ],
    explanation: 'Alimentarse bien, descansar y hacer ejercicio son hábitos saludables.',
    hint: 'Son cosas que hacemos habitualmente.',
  },
  {
    id: 'q14',
    question: '¿Cuál de estas frases es correcta?',
    difficulty: 'hard',
    points: 20,
    answers: [
      { id: 'a', text: 'La salud solo depende de que el cuerpo funcione bien', correct: false },
      { id: 'b', text: 'La salud tiene aspectos físicos, mentales y sociales', correct: true },
      { id: 'c', text: 'La salud social y la mental significan lo mismo', correct: false },
    ],
    explanation: 'Para sentirnos bien debemos tener en cuenta la salud física, mental y social.',
    hint: 'Recuerda las tres partes estudiadas.',
  },
  {
    id: 'q15',
    question: '¿Qué profesional puede ayudarnos a cuidar nuestra salud en una revisión infantil?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Un pediatra o una pediatra', correct: true, emoji: '👩‍⚕️' },
      { id: 'b', text: 'Un piloto', correct: false, emoji: '✈️' },
      { id: 'c', text: 'Un carpintero', correct: false, emoji: '🪚' },
    ],
    explanation:
      'Los pediatras son profesionales sanitarios especializados en la salud de niños y niñas.',
    hint: 'Piensa en quién te atiende en el centro de salud.',
  },
  {
    id: 'q16',
    question: '¿Dónde podemos acudir cuando necesitamos atención sanitaria?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'A centros de salud, hospitales o servicios de urgencias',
        correct: true,
        emoji: '🏥',
      },
      { id: 'b', text: 'Solo al colegio', correct: false, emoji: '🏫' },
      { id: 'c', text: 'A una tienda de juguetes', correct: false, emoji: '🧸' },
    ],
    explanation: 'Existen distintos servicios sanitarios para atender los problemas de salud.',
    hint: 'Busca lugares donde trabajan profesionales sanitarios.',
  },
  {
    id: 'q17',
    question:
      'Paula está preocupada y habla con una persona de confianza sobre cómo se siente. ¿Qué aspecto de su salud está cuidando especialmente?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'La salud mental', correct: true, emoji: '💛' },
      { id: 'b', text: 'La salud física', correct: false, emoji: '💪' },
      { id: 'c', text: 'Ninguno', correct: false, emoji: '❌' },
    ],
    explanation:
      'Hablar de nuestras emociones y aprender a manejarlas ayuda a cuidar la salud mental.',
    hint: 'Se refiere a cómo se siente Paula.',
  },
  {
    id: 'q18',
    question: '¿Qué tienen en común los hábitos saludables, las revisiones y las vacunas?',
    difficulty: 'hard',
    points: 20,
    answers: [
      { id: 'a', text: 'Son formas de prevención', correct: true, emoji: '🛡️' },
      { id: 'b', text: 'Solo se hacen cuando estamos enfermos', correct: false },
      { id: 'c', text: 'Son tipos de salud social', correct: false },
    ],
    explanation: 'Las tres son acciones que contribuyen a prevenir problemas y cuidar la salud.',
    hint: 'Piensa en el título de la segunda parte del tema.',
  },
  {
    id: 'q19',
    question: '¿Cuál de estos lugares es un servicio sanitario?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Un centro de salud', correct: true, emoji: '🩺' },
      { id: 'b', text: 'Un cine', correct: false, emoji: '🎬' },
      { id: 'c', text: 'Una biblioteca', correct: false, emoji: '📚' },
    ],
    explanation: 'Los centros de salud son servicios sanitarios.',
    hint: 'Piensa en un lugar al que acudimos para recibir atención sanitaria.',
  },
  {
    id: 'q20',
    question: '¿Qué tienen en común un centro de salud, un hospital y un servicio de urgencias?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Son servicios sanitarios', correct: true, emoji: '🏥' },
      { id: 'b', text: 'Son lugares para practicar deporte', correct: false, emoji: '⚽' },
      { id: 'c', text: 'Son centros educativos', correct: false, emoji: '🏫' },
    ],
    explanation: 'Los tres son servicios sanitarios que ayudan a atender problemas de salud.',
    hint: 'Todos están relacionados con la atención de nuestra salud.',
  },
  {
    id: 'q21',
    question: '¿Quién trabaja en los servicios sanitarios cuidando nuestra salud?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Profesionales especializados', correct: true, emoji: '👩‍⚕️' },
      { id: 'b', text: 'Solo deportistas', correct: false, emoji: '🏃' },
      { id: 'c', text: 'Solo músicos', correct: false, emoji: '🎵' },
    ],
    explanation:
      'En los servicios sanitarios trabajan profesionales especializados en cuidar nuestra salud.',
    hint: 'Piensa en las personas preparadas para atender problemas de salud.',
  },
  {
    id: 'q22',
    question:
      'Si necesitamos atención urgente por un problema de salud, ¿qué servicio aparece entre los que hemos estudiado?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'El servicio de urgencias', correct: true, emoji: '🚑' },
      { id: 'b', text: 'Una tienda', correct: false, emoji: '🛍️' },
      { id: 'c', text: 'Un museo', correct: false, emoji: '🏛️' },
    ],
    explanation: 'Los servicios de urgencias son uno de los servicios sanitarios estudiados.',
    hint: 'Su propio nombre indica que atiende situaciones urgentes.',
  },
  {
    id: 'q23',
    question: '¿Qué frase describe mejor la salud física?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Nuestro cuerpo funciona correctamente y realizamos actividades sin dolor ni dificultades',
        correct: true,
        emoji: '🏃‍♀️',
      },
      { id: 'b', text: 'Nos llevamos bien con otras personas', correct: false, emoji: '👫' },
      { id: 'c', text: 'Sabemos manejar nuestras emociones', correct: false, emoji: '😊' },
    ],
    explanation: 'La salud física está relacionada con el funcionamiento de nuestro cuerpo.',
    hint: 'Física = cuerpo.',
  },
  {
    id: 'q24',
    question: '¿Qué frase describe mejor la salud mental?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Estamos contentos con nosotros mismos y sabemos manejar nuestras emociones',
        correct: true,
        emoji: '😊',
      },
      { id: 'b', text: 'Nuestro cuerpo corre muy rápido', correct: false, emoji: '🏃' },
      { id: 'c', text: 'Tenemos muchos juguetes', correct: false, emoji: '🧸' },
    ],
    explanation:
      'La salud mental está relacionada con cómo nos sentimos y cómo manejamos nuestras emociones.',
    hint: 'Mental = emociones.',
  },
  {
    id: 'q25',
    question: '¿Qué frase describe mejor la salud social?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Nos relacionamos bien con las demás personas', correct: true, emoji: '🤝' },
      { id: 'b', text: 'Nunca necesitamos dormir', correct: false, emoji: '😴' },
      { id: 'c', text: 'Nuestro cuerpo no siente dolor', correct: false, emoji: '💪' },
    ],
    explanation: 'La salud social se refiere a nuestras relaciones con otras personas.',
    hint: 'Social = los demás.',
  },
  {
    id: 'q26',
    question: '¿Cuál de estas acciones NO es una forma de prevención de las que hemos estudiado?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Esperar a tener un problema para empezar a cuidarnos',
        correct: true,
        emoji: '⌛',
      },
      { id: 'b', text: 'Mantener hábitos saludables', correct: false, emoji: '🥗' },
      { id: 'c', text: 'Acudir a revisiones médicas', correct: false, emoji: '🩺' },
    ],
    explanation: 'La prevención consiste en actuar para intentar evitar problemas de salud.',
    hint: 'Busca la opción que ocurre después, no antes.',
  },
  {
    id: 'q27',
    question: 'Dormir lo necesario, alimentarnos bien y hacer actividad física son ejemplos de...',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Hábitos saludables', correct: true, emoji: '🌱' },
      { id: 'b', text: 'Servicios sanitarios', correct: false, emoji: '🏥' },
      { id: 'c', text: 'Vacunas', correct: false, emoji: '💉' },
    ],
    explanation: 'Son costumbres que ayudan a mantenernos sanos.',
    hint: 'Son acciones que repetimos habitualmente para cuidarnos.',
  },
  {
    id: 'q28',
    question: '¿Tenemos que esperar a encontrarnos mal para hacer una revisión médica?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'No, las revisiones también forman parte de la prevención',
        correct: true,
        emoji: '🩺',
      },
      { id: 'b', text: 'Sí, siempre', correct: false, emoji: '🤒' },
    ],
    explanation:
      'Las revisiones médicas ayudan a comprobar nuestro estado de salud y forman parte de la prevención.',
    hint: 'Prevenir significa actuar antes de que aparezca un problema.',
  },
  {
    id: 'q29',
    question: 'Completa la idea: física, mental y social son...',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Tres aspectos de la salud', correct: true, emoji: '🌟' },
      { id: 'b', text: 'Tres tipos de hospitales', correct: false, emoji: '🏥' },
      { id: 'c', text: 'Tres vacunas', correct: false, emoji: '💉' },
    ],
    explanation: 'La salud comprende los aspectos físico, mental y social.',
    hint: 'Son las tres partes que aparecen al explicar qué es la salud.',
  },
  {
    id: 'q30',
    question: 'Elige el resumen correcto sobre la prevención.',
    difficulty: 'hard',
    points: 20,
    answers: [
      {
        id: 'a',
        text: 'Los hábitos saludables, las revisiones médicas y las vacunas nos ayudan a cuidar la salud',
        correct: true,
        emoji: '🛡️',
      },
      {
        id: 'b',
        text: 'Prevenir significa no acudir nunca a servicios sanitarios',
        correct: false,
        emoji: '🚫',
      },
      {
        id: 'c',
        text: 'Solo podemos cuidar la salud cuando ya estamos enfermos',
        correct: false,
        emoji: '🤒',
      },
    ],
    explanation:
      'La prevención reúne acciones que realizamos para cuidar nuestra salud y tratar de evitar problemas.',
    hint: 'Recuerda las tres formas de prevención estudiadas.',
  },
  {
    id: 'q31',
    question: '¿De qué origen es la leche?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'animal', correct: true },
      { id: 'b', text: 'vegetal', correct: false },
      { id: 'c', text: 'mineral', correct: false },
    ],
    explanation: 'La leche procede de animales, por eso es de origen animal.',
    hint: 'Piensa de dónde obtenemos la leche.',
  },
  {
    id: 'q32',
    question: '¿De qué origen son las frutas y las verduras?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'vegetal', correct: true },
      { id: 'b', text: 'animal', correct: false },
      { id: 'c', text: 'mineral', correct: false },
    ],
    explanation: 'Las frutas y verduras proceden de plantas.',
    hint: 'Piensa en dónde crecen.',
  },
  {
    id: 'q33',
    question: '¿Qué alimento es de origen mineral?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'El agua', correct: true },
      { id: 'b', text: 'El huevo', correct: false },
      { id: 'c', text: 'La manzana', correct: false },
    ],
    explanation: 'El agua y la sal son alimentos de origen mineral.',
    hint: 'No procede ni de un animal ni de una planta.',
  },
  {
    id: 'q34',
    question: '¿Cuál es la función principal de los alimentos energéticos?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Proporcionar energía', correct: true },
      { id: 'b', text: 'Reparar únicamente los huesos', correct: false },
      { id: 'c', text: 'Relacionarnos con los demás', correct: false },
    ],
    explanation:
      'Los alimentos energéticos proporcionan energía para la actividad física y para pensar.',
    hint: 'Su nombre da una pista.',
  },
  {
    id: 'q35',
    question: '¿Cuál de estos es un alimento energético?',
    difficulty: 'hard',
    points: 20,
    answers: [
      { id: 'a', text: 'El pan', correct: true },
      { id: 'b', text: 'La lechuga', correct: false },
      { id: 'c', text: 'El pescado', correct: false },
    ],
    explanation: 'El pan, el arroz, la pasta y los aceites son ejemplos de alimentos energéticos.',
    hint: 'Piensa en los alimentos que aportan energía.',
  },
  {
    id: 'q36',
    question: '¿Para qué sirven principalmente los alimentos constructores?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Para crecer y reparar tejidos', correct: true },
      { id: 'b', text: 'Para sustituir el agua', correct: false },
      { id: 'c', text: 'Para evitar dormir', correct: false },
    ],
    explanation: 'Los constructores aportan materiales para crecer y reparar los tejidos.',
    hint: 'Construir = crecer y reparar.',
  },
  {
    id: 'q37',
    question: '¿Cuál de estos grupos contiene alimentos reguladores?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Frutas, verduras y hortalizas', correct: true },
      { id: 'b', text: 'Pan, pasta y arroz', correct: false },
      { id: 'c', text: 'Carne, pescado y huevos', correct: false },
    ],
    explanation:
      'Las frutas, verduras y hortalizas aportan sustancias que regulan el funcionamiento del organismo.',
    hint: 'Son alimentos vegetales muy presentes en una dieta saludable.',
  },
  {
    id: 'q38',
    question: '¿Qué significa que un alimento sea mínimamente procesado?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Que no tiene ingredientes añadidos y solo ha pasado procesos sencillos',
        correct: true,
      },
      { id: 'b', text: 'Que siempre lleva mucho azúcar', correct: false },
      { id: 'c', text: 'Que se fabrica completamente a partir de otros alimentos', correct: false },
    ],
    explanation:
      'Los procesos sencillos facilitan su consumo o conservación sin cambiar esencialmente el alimento.',
    hint: 'Piensa en limpiar, hervir, pelar o embotellar.',
  },
  {
    id: 'q39',
    question: '¿Qué caracteriza a los alimentos procesados?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'Se les añaden sustancias como sal, azúcar, aceite o conservantes',
        correct: true,
      },
      { id: 'b', text: 'Nunca han sufrido ningún proceso', correct: false },
      { id: 'c', text: 'Solo pueden ser frutas', correct: false },
    ],
    explanation:
      'Los procesados parten de alimentos naturales o mínimamente procesados y reciben ingredientes añadidos.',
    hint: 'La clave está en lo que se añade.',
  },
  {
    id: 'q40',
    question: '¿Qué son los alimentos ultraprocesados?',
    difficulty: 'hard',
    points: 20,
    answers: [
      {
        id: 'a',
        text: 'Productos elaborados industrialmente a partir de otros alimentos',
        correct: true,
      },
      { id: 'b', text: 'Alimentos recién recogidos del campo', correct: false },
      { id: 'c', text: 'Solo agua y sal', correct: false },
    ],
    explanation: 'En los ultraprocesados los alimentos originales se transforman mucho.',
    hint: 'Piensa en productos industriales como bollería o comida rápida.',
  },
  {
    id: 'q41',
    question: 'Para una dieta saludable, ¿qué alimentos conviene consumir principalmente?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Naturales o mínimamente procesados', correct: true },
      { id: 'b', text: 'Ultraprocesados', correct: false },
      { id: 'c', text: 'Solo dulces', correct: false },
    ],
    explanation:
      'Una dieta saludable debe basarse principalmente en alimentos naturales o mínimamente procesados.',
    hint: 'Cuanto menos transformados, mejor como base de la dieta.',
  },
  {
    id: 'q42',
    question: '¿Qué es la dieta?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'La cantidad y el tipo de alimentos que una persona toma cada día',
        correct: true,
      },
      { id: 'b', text: 'Una comida especial solo para adelgazar', correct: false },
      { id: 'c', text: 'Únicamente el desayuno', correct: false },
    ],
    explanation: 'Todas las personas tenemos una dieta: es lo que comemos habitualmente.',
    hint: 'No significa necesariamente adelgazar.',
  },
  {
    id: 'q43',
    question: '¿Qué opción es más recomendable con la fruta?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Tomarla entera', correct: true },
      { id: 'b', text: 'Tomarla siempre en zumo', correct: false },
      { id: 'c', text: 'Sustituirla por refrescos', correct: false },
    ],
    explanation:
      'Se recomienda tomar frutas y verduras cada día y preferir la fruta entera a zumos o batidos.',
    hint: 'Piensa en cómo conserva mejor todas sus partes.',
  },
  {
    id: 'q44',
    question: '¿Cómo se recomienda elegir el pan, la pasta y el arroz?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Integrales', correct: true },
      { id: 'b', text: 'Siempre azucarados', correct: false },
      { id: 'c', text: 'Fritos', correct: false },
    ],
    explanation: 'Se recomienda que pan, pasta y arroz sean integrales.',
    hint: 'Es una palabra que aparece en la recomendación del plato saludable.',
  },
  {
    id: 'q45',
    question: '¿Qué grasa es preferible utilizar?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Aceite de oliva', correct: true },
      { id: 'b', text: 'Mantequilla en grandes cantidades', correct: false },
      { id: 'c', text: 'Grasa animal siempre', correct: false },
    ],
    explanation:
      'Se aconseja utilizar aceites vegetales, como el de oliva, y evitar las grasas de origen animal.',
    hint: 'Piensa en un aceite vegetal.',
  },
  {
    id: 'q46',
    question: '¿Qué alimento vegetal muy completo se recomienda consumir?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Legumbres', correct: true },
      { id: 'b', text: 'Chucherías', correct: false },
      { id: 'c', text: 'Embutidos', correct: false },
    ],
    explanation:
      'Las legumbres son un alimento vegetal muy completo y ayudan a reducir el consumo de alimentos de origen animal.',
    hint: 'Lentejas, garbanzos y judías pertenecen a este grupo.',
  },
  {
    id: 'q47',
    question: 'Entre los alimentos de origen animal, ¿qué se recomienda preferir?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Pescado o aves', correct: true },
      { id: 'b', text: 'Carne roja y embutidos', correct: false },
      { id: 'c', text: 'Solo mantequilla', correct: false },
    ],
    explanation: 'Se recomienda preferir pescado o aves y reducir carne roja y embutidos.',
    hint: 'Busca la opción que el tema recomienda aumentar frente a carne roja.',
  },
  {
    id: 'q48',
    question: '¿Cuánta agua indica el tema que debemos beber cada día?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Entre 1,5 y 2 litros', correct: true },
      { id: 'b', text: 'Un vaso a la semana', correct: false },
      { id: 'c', text: 'Más de 5 litros obligatoriamente', correct: false },
    ],
    explanation: 'El tema recomienda beber entre 1,5 y 2 litros de agua al día.',
    hint: 'Está entre uno y dos litros, aproximadamente.',
  },
  {
    id: 'q49',
    question: '¿Por qué conviene evitar el exceso de alimentos azucarados?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Porque demasiado azúcar puede favorecer problemas como caries o sobrepeso',
        correct: true,
      },
      { id: 'b', text: 'Porque el azúcar impide aprender a leer', correct: false },
      { id: 'c', text: 'Porque todos los alimentos dulces son de origen mineral', correct: false },
    ],
    explanation: 'El exceso de azúcar puede relacionarse con problemas como sobrepeso o caries.',
    hint: 'Piensa en dientes y exceso de peso.',
  },
  {
    id: 'q50',
    question: '¿Cuál es un beneficio del ejercicio físico?',
    difficulty: 'hard',
    points: 20,
    answers: [
      { id: 'a', text: 'Fortalece huesos y músculos', correct: true },
      { id: 'b', text: 'Hace innecesario dormir', correct: false },
      { id: 'c', text: 'Evita que necesitemos alimentarnos', correct: false },
    ],
    explanation: 'El ejercicio fortalece los huesos y los músculos, entre otros beneficios.',
    hint: 'Piensa en cómo mejora nuestro cuerpo.',
  },
  {
    id: 'q51',
    question: '¿Qué órganos se benefician del ejercicio según el tema?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'El corazón y los pulmones', correct: true },
      { id: 'b', text: 'Solo los ojos', correct: false },
      { id: 'c', text: 'Solo las orejas', correct: false },
    ],
    explanation: 'El ejercicio es bueno para el corazón y los pulmones.',
    hint: 'Uno bombea sangre y los otros participan en la respiración.',
  },
  {
    id: 'q52',
    question: '¿Qué debemos hacer antes de empezar a hacer ejercicio?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Calentar', correct: true },
      { id: 'b', text: 'Estirar solo al principio y nunca calentar', correct: false },
      { id: 'c', text: 'Empezar al máximo sin preparación', correct: false },
    ],
    explanation: 'El calentamiento antes de empezar ayuda a prevenir lesiones.',
    hint: 'Prepara el cuerpo antes del esfuerzo.',
  },
  {
    id: 'q53',
    question: '¿Qué debemos hacer al terminar el ejercicio?',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Realizar estiramientos', correct: true },
      { id: 'b', text: 'Ponernos la mochila', correct: false },
      { id: 'c', text: 'Comer chucherías', correct: false },
    ],
    explanation: 'El tema recomienda realizar ejercicios de estiramiento al terminar.',
    hint: 'Es la acción final que ayuda a cuidar músculos.',
  },
  {
    id: 'q54',
    question: 'Si durante el ejercicio te sientes muy fatigado, ¿qué debes hacer?',
    difficulty: 'easy',
    points: 10,
    answers: [
      { id: 'a', text: 'Descansar', correct: true },
      { id: 'b', text: 'Seguir sin parar', correct: false },
      { id: 'c', text: 'Quitar las protecciones', correct: false },
    ],
    explanation: 'Debemos descansar cuando nos sintamos muy fatigados.',
    hint: 'Escucha a tu cuerpo.',
  },
  {
    id: 'q55',
    question: '¿Cómo debemos llevar una mochila tradicional?',
    difficulty: 'hard',
    points: 20,
    answers: [
      { id: 'a', text: 'Con los dos tirantes bien ajustados', correct: true },
      { id: 'b', text: 'Colgada siempre de un solo hombro', correct: false },
      { id: 'c', text: 'En la mano con todo el peso a un lado', correct: false },
    ],
    explanation: 'Los dos tirantes reparten mejor el peso y ayudan a cuidar la espalda.',
    hint: 'Hay que repartir el peso.',
  },
  {
    id: 'q56',
    question: '¿Cuál es una postura correcta al sentarnos?',
    difficulty: 'medium',
    points: 15,
    answers: [
      {
        id: 'a',
        text: 'Pies apoyados en el suelo y espalda recta contra el respaldo',
        correct: true,
      },
      { id: 'b', text: 'Espalda torcida y pies en el aire', correct: false },
      { id: 'c', text: 'Tumbados sobre la mesa', correct: false },
    ],
    explanation:
      'Una postura correcta mantiene los pies apoyados y la espalda recta contra el respaldo.',
    hint: 'Piensa en apoyar bien el cuerpo.',
  },
  {
    id: 'q57',
    question: '¿Qué postura para dormir recomienda el tema?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'De lado o bocarriba, con la cabeza apoyada y las rodillas flexionadas',
        correct: true,
      },
      { id: 'b', text: 'Siempre boca abajo sin almohada', correct: false },
      { id: 'c', text: 'Sentados en una silla', correct: false },
    ],
    explanation:
      'El tema recomienda dormir de lado o bocarriba con cabeza apoyada y rodillas flexionadas.',
    hint: 'Hay dos posiciones recomendadas.',
  },
  {
    id: 'q58',
    question: 'Leer o visitar un museo son ejemplos de...',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Ocio cultural', correct: true },
      { id: 'b', text: 'Ocio deportivo', correct: false },
      { id: 'c', text: 'Ocio electrónico', correct: false },
    ],
    explanation: 'Las actividades culturales incluyen leer, visitar museos o ir al cine.',
    hint: 'No requiere necesariamente deporte ni pantalla.',
  },
  {
    id: 'q59',
    question: 'Jugar a la consola es un ejemplo de...',
    difficulty: 'medium',
    points: 15,
    answers: [
      { id: 'a', text: 'Ocio electrónico', correct: true },
      { id: 'b', text: 'Ocio cultural', correct: false },
      { id: 'c', text: 'Revisión médica', correct: false },
    ],
    explanation: 'La consola es una actividad de ocio electrónico.',
    hint: 'Se realiza con un dispositivo electrónico.',
  },
  {
    id: 'q60',
    question: '¿Cuándo es saludable nuestro ocio?',
    difficulty: 'easy',
    points: 10,
    answers: [
      {
        id: 'a',
        text: 'Cuando combinamos actividades variadas y controlamos el tiempo de ocio electrónico',
        correct: true,
      },
      { id: 'b', text: 'Cuando solo usamos pantallas todo el tiempo libre', correct: false },
      { id: 'c', text: 'Cuando nunca hacemos actividades físicas ni culturales', correct: false },
    ],
    explanation:
      'Un ocio saludable combina actividades diversas y limita el tiempo dedicado al ocio electrónico.',
    hint: 'La variedad y el tiempo controlado son las claves.',
  },
];
